steps:
    # 1. Build the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA', '.']

    # 2. Push to Artifact Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA']
    
    # 3. Deploy backend
    - name: 'gcr.io/cloud-builders/cloud-sdk'
      entrypoint: gcloud
      args:
        - 'run'
        - 'deploy'
        - 'chicago-backend'
        - '--image'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA'
        - 'region'
        - '$_REGION'
    
    # 4. Deploy frontend
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
        - 'run'
        - 'deploy'
        - 'chicago-frontend'
        - '--image'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA'
        - '--region'
        - '$_REGION'

substitutions:
  _REGION: us-central1
  
options:
  logging: CLOUD_LOGGING_ONLY