steps:
# ----------------
# CI
# ----------------
    # 1. Build the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args: [
        'build', 
        '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA', 
        '--cache-from', '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:latest',
        '.'
      ]
      
    # 2. Push to Artifact Reg
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA']
    
    # 3. Tag the image as 'latest' for the next build's cache
    - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'tag'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA'
        - '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:latest'

    # 4. Push the 'latest' image to Artifact Reg
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:latest']

# ----------------
# CD
# ----------------

    # 5. Deploy backend
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
        - 'run'
        - 'deploy'
        - 'chicago-backend'
        - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA'
        - '--command=python'
        - '--args=-m,uvicorn,app.main:app,--host,0.0.0.0,--port,8000'
        - '--region=$_REGION'
        - '--port=8000'
        - '--env-vars-file=env.yaml'
        - '--timeout=300'
    
    # 6. Deploy frontend
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
        - 'run'
        - 'deploy'
        - 'chicago-frontend'
        - '--service-account=chicago-frontend-sa@$PROJECT_ID.iam.gserviceaccount.com'
        - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/chicago-repo/chicago-app:$COMMIT_SHA'
        - '--command=python'
        - '--args=-m,streamlit,run,frontend/Home.py,--server.port=8501,--server.address=0.0.0.0,--server.headless=true,--server.fileWatcherType=none'
        - '--region=$_REGION'
        - '--port=8501'
        - '--env-vars-file=env.yaml'
        - '--timeout=300'
substitutions:
  _REGION: us-central1
  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'